# Site settings
title: Clayton
header-img: img/home-bg.jpg
email: crs.hunter@gmail.com
copyright_name: Clayton's webpage
description: "Clayton's personal webpage."
baseurl: ""
url: "https://claytonrsh.com"
twitter_username: claytonrsh
github_username:  claytonrsh
facebook_username:  claytonrsh
email_username:

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id:UA-101656571-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
