# Site settings
title: Clayton
header-img: img/home-bg.jpg
email: crs.hunter@gmail.com
copyright_name: Clayton's webpage
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://claytonrsh.github.io"
twitter_username: claytonrsh
github_username:  claytonrsh
facebook_username:  claytonrsh
email_username: 

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
